### ISSUE TITLE
Issue with Bloodmoon on a Server

### ISSUE THREAD

**Issue by DracoC2M** [Urkaz/UrkazMoonTools#1]
Hi Urkaz,

since yesterday I'm using this mod. In the description you wrote, that it is compatible with Bloodmoon. But I found out, that the Lunar Clock does not work if I play on my Minecraft Server. The Lunar Clock seems to work asynchronous to Bloodmoon. I can see the moon phase but not if it is red or white. Sometimes it shows a Bloodmoon if it is a normal one. And sometimes it shows the normal moon if the bloodmoon event is running. 

Best regards,

Marcel

**Comment by Urkaz** [comment]
Thanks for pointing this, I was using the instance of the mod that is only created when playing in singleplayer, so on servers, it was always null so the red effect was not applied or applied incorrectly.

It should be fixed in version 1.5.
