### ISSUE TITLE
Enhanced Celestials compatability not working on 1.19.2

### ISSUE THREAD

**Issue by valchiara** [Urkaz/UrkazMoonTools#10]
The lunar clock does not change its color according to the lunar event.

Minecraft 1.19.2
Forge 43.3.8
Urkaz Moon Tools 2.0.31
Enhanced Celestials 1.19.2-2.1.0.6

![img-2024-02-26-13-23-44](https://github.com/Urkaz/UrkazMoonTools/assets/108143059/b4a40630-42da-433c-8755-1ef562928a5a)

**Comment by Urkaz** [comment]
Hi, thanks for your report and sorry for the late response (I hadn't received any notification from GitHub :/)
This issue was affecting all versions with EC support. I'll release a fix in the following hours.

**Comment by Urkaz** [comment]
It should be fixed now :)
