### ISSUE TITLE
The mod won't load with Enhanced Celestials.

### ISSUE THREAD

**Issue by Zeykehasnt** [Urkaz/UrkazMoonTools#11]
![javaw_f0W8h638Sk](https://github.com/user-attachments/assets/af0cd150-12bc-45a6-a2c8-cf6b551317b9)

https://pastebin.com/6YGDmvEz

**Comment by Urkaz** [comment]
Hi, thanks for the report!
For some reason, Enhanced Celestials changed how identifies their versions only on Forge and I missed this when testing it (having to test the mod on 5 Minecraft versions for 2-3 mod loaders + all the compatibility and stuff is a bit of a nightmare sometimes, tbh 😅).
I published a new version only for 1.20.1-forge (2.1.1-40) fixing this.
