### ISSUE TITLE
lunar clock rendering issue crash

### ISSUE THREAD

**Issue by Biviho** [Urkaz/UrkazMoonTools#4]
there is a rendering issue that cause a crash while crafting the item in a high modpack environment.
crashlog: https://pastebin.com/cNnbL2Vz

in a low modpack environment the crash is caused when trying to see the recipe via jei.
crashlog: https://pastebin.com/JXBVD3cY

in both istance the clock is not visible in jei but there is a void spot in it's place

**Comment by Urkaz** [comment]
Hi @Biviho , thanks for your report and sorry for the late response!
This crash should be fixed on the last version:
https://github.com/Urkaz/UrkazMoonTools/releases/tag/v1.8

Please, check if the problem persists and if you see any other issue, tell me :)
