### ISSUE TITLE
Crimson Moon Compat?

### ISSUE THREAD

**Issue by ConqAra** [Urkaz/UrkazMoonTools#5]
Some love for [crimson moon](https://www.curseforge.com/minecraft/mc-mods/crimson-moon) as well?

**Comment by Urkaz** [comment]
Hi, I didn't know the Crimson Moon mod, I'll take a look at it and see if I can add support for it.
Thank you!

**Comment by Urkaz** [comment]
The mod will be compatible with CrimsonMoon in the next release for 1.19 and 1.19.1 :D
