### ISSUE TITLE
[Suggestion] Lunar Compat

### ISSUE THREAD

**Issue by Ultimushadow** [Urkaz/UrkazMoonTools#6]
Hey there, I was planning on using Enhanced Celestials in my pack, but the mod hasn't been updated in a while and doesn't work with a lot of other mods. I switched to Lunar https://modrinth.com/mod/lunar which has a similar vibe. I haven't had the time to double check but from a quick pass it looks like Lunar isn't supported - I think this would be a great mod to add support for!

**Comment by Urkaz** [comment]
Hi, thanks for the suggestion, I didn't know about Lunar!
I'll take a look at it and see what can I do to support it ;)

**Comment by Urkaz** [comment]
This will be available in the next version! :D
