### ISSUE TITLE
Fail to load on 2.0.30 Forge 1.19.2

### ISSUE THREAD

**Issue by ChiefLogan3010** [Urkaz/UrkazMoonTools#8]
When trying to load the game, it errors and cancels loading with the error message below:

https://gist.github.com/ChiefLogan3010/168e5db465019cc6e70e49858a7d2299

Minecraft 1.19.2
Forge 43.3.2
Urkaz Moon Tools 2.0.30

**Comment by Urkaz** [comment]
Hi, thanks for your report. I'll take a look asap and release a fix.

**Comment by Urkaz** [comment]
This should be fixed in 2.0.31.
I was checking if a mod is installed, but on Forge, the list was not initialized at that point, so I had to use another method.
