### ISSUE TITLE
Midnight / 12AM is shown as "0:XX".

### ISSUE THREAD

**Issue by PlayfulPiano** [Urkaz/UrkazMoonTools#9]
![image](https://github.com/Urkaz/UrkazMoonTools/assets/3158887/5477451a-ab6b-40d8-814f-91aeca3605ac)

This issue doesn't happen when it's 12PM. I'm assuming it's probably remnants of 24h formatting.

**Comment by Urkaz** [comment]
Hi! I think this is an issue of OdysseyHUD. UrkazMoonTools is not displaying any HUD right now @PlayfulPiano.
You can find their issue tracker here: https://github.com/Dplayend/OdysseyHUD/issues

-- Urkaz

**Comment by PlayfulPiano** [comment]
yeah whoops wrong mod report
